Update terraform planner role to roles/viewer
kyma-project/test-infra pull request #10007
Opened 2024-03-04 10:44 UTC by KacperMalachowski

**Description**

I wrong;y assu,e that browser role can browser data about resources. Fix it up quickly with viewer role that can view what resource state is.

Changes proposed in this pull request:

- Update role to viewer, so the planenr SA will gain access to reources not only reource list

**Related issue(s)**

/kind bug
/area automation

2024-03-04 10:46 UTC, Sawthis submitted a review, later dismissed

2024-03-04 10:53 UTC, KacperMalachowski commented
/hold

2024-03-04 10:58 UTC, KacperMalachowski commented
/unhold

2024-03-07 14:56 UTC, dekiel commented on configs/terraform/environments/prod/terraform-service-accounts.tf
> +}
Do we still need this custom role?

2024-03-07 14:57 UTC, dekiel requested changes
See comment about custom role.

2024-03-07 20:38 UTC, KacperMalachowski commented on configs/terraform/environments/prod/terraform-service-accounts.tf
> +}
No, my fault, removed.

2024-03-07 21:28 UTC, dekiel approved these changes

2024-03-07 21:30 UTC, merged