Read ado pat from gcp secret manager in image-builder reusable workflow.
kyma-project/test-infra pull request #10860
Opened 2024-05-29 00:22 UTC by dekiel

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2024-05-29 09:58 UTC, dekiel commented
The PR will be force merged because it is suppose to fix image-builder reusable workflow. Ignore failed `pull-image-builder-test / test_image_builder / Build image` context.

2024-05-31 04:02 UTC, KacperMalachowski requested changes

2024-05-31 04:02 UTC, KacperMalachowski commented on configs/terraform/environments/prod/image-builder.tf
> +    "principal://iam.googleapis.com/${module.gh_com_kyma_project_workload_identity_federation.pool_name}/subject/repository_id:${data.github_repository.test_infra.repo_id}:repository_owner_id:${data.
```suggestion
    "principal://iam.googleapis.com/${module.gh_com_kyma_project_workload_identity_federation.pool_name}/subject/repository_id:${data.github_repository.test_infra.repo_id}:repository_owner_id:${data.github_organization.kyma-project.id}:workflow:${var.image_builder_reusable_workflow_name}"
```

2024-05-31 08:13 UTC, KacperMalachowski approved these changes

2024-05-31 08:14 UTC, KacperMalachowski approved these changes

2024-05-31 08:47 UTC, KacperMalachowski commented
The PR looks affected by: https://github.com/orgs/community/discussions/58535
@dekiel Can you please close and reopen it? As it seems only known and working workaround for that strange github issue...

Or if you prefer you can merge it right away, because you need force anyway. From my side: LGTM.

2024-05-31 08:52 UTC, merged