Remove schema-migrator related Prow jobs
kyma-project/test-infra pull request #11743
Opened 2024-08-29 09:10 UTC by MarekMichali

Changes proposed in this pull request:

- Remove schema-migrator related Prow jobs

**Related issue(s)**

2024-08-30 13:59 UTC, dekiel submitted a review, later dismissed

2024-09-03 09:33 UTC, Sawthis requested changes
Please resolve conflicts.

2024-09-03 14:21 UTC, dekiel approved these changes

2024-09-03 15:04 UTC, Sawthis approved these changes

2024-09-03 15:04 UTC, Sawthis approved these changes

2024-09-03 15:04 UTC, merged