Adjust terraform to store cleanup policies
kyma-project/test-infra pull request #11915
Opened 2024-09-16 12:20 UTC by akiioto

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2024-09-17 09:22 UTC, dekiel requested changes

2024-09-17 09:22 UTC, dekiel commented on configs/terraform/environments/prod/image-builder-variables.tf
Please consider creating object type variable to collect all artifact registry details together.

2024-09-17 09:24 UTC, akiioto commented on configs/terraform/modules/service-account-keys-cleaner/main.tf
> +    uri         = format("%s/?project=%s&age=%s", google_cloud_run_service.service_account_keys_cleaner.status[0].url, data.google_project.project.project_id, var.service_account_key_latest_version_m
To match the value stored in GC. Otherwise terraform plan shows difference.

2024-10-02 10:48 UTC, KacperMalachowski commented on configs/terraform/environments/prod/image-builder.tf
> +  member     = var.dockerhub_mirror_member
Added import statement and resource description

2024-10-02 10:48 UTC, KacperMalachowski commented on configs/terraform/environments/prod/image-builder-variables.tf
> +}
Rmeoved

2024-10-02 19:27 UTC, dekiel approved these changes
I did realize that using variables for import resources in config might be dangerous. If someone will change variables values, the import will be executed with different values. I think we should use an explicit values in import or remove it from config.

2024-10-02 19:29 UTC, merged