Migrate cleaners
kyma-project/test-infra pull request #12065
Opened 2024-10-03 14:53 UTC by KacperMalachowski

**Description**

Instead of migrating gcr-cleaner container, we switch to google artifact registry's cleanup policies.
Additional cleanup (removing actual prowjob) will be done toghetehr with enabling clean up policies after testing period (2-3 days.

Changes proposed in this pull request:

- Add configuration for existing registries
- Add cleanup policies using dynamic keyword, so they can be modified using variables
- Remove assetsstore cleanup job, as the buckets are not used since 2023.

**Related issue(s)**

See: #9765

2024-10-03 22:20 UTC, dekiel requested changes
Did you consider to stick to the best practice about `dynamic` block usage? https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks#best-practices-for-dynamic-blocks

2024-10-04 06:21 UTC, KacperMalachowski commented
> Did you consider to stick to the best practice about `dynamic` block usage? https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks#best-practices-for-dynamic-blocks

Yes, the idea behind current setup was that we can configure it using the variables.
The most of the current setup was to avoid multiple cleanup_policies blocks, but I will switch to the first idea then.

2024-10-04 07:26 UTC, KacperMalachowski commented
/retest

2024-10-04 09:55 UTC, dekiel approved these changes

2024-10-04 09:57 UTC, merged