Removed unused prowjob scenario docs.
kyma-project/test-infra pull request #12142
Opened 2024-10-14 15:34 UTC by dekiel

Removed limited tags on pr images notice.

**Related issue(s)**
See #10415

2024-10-14 16:11 UTC, IwonaLanger approved these changes

2024-10-15 05:36 UTC, Sawthis requested changes
This PR contains only formatting changes.

2024-10-15 13:15 UTC, dekiel commented
Added missing changes. Added more details about default tags generated by the tool. Users duplicates tags by adding custom tags with value the same as default tag.

2024-10-15 13:38 UTC, Sawthis submitted a review, later dismissed

2024-10-15 14:03 UTC, IwonaLanger commented on cmd/image-builder/README.md
> +The Image Builder supports two default tags:
```suggestion
Image Builder supports two default tags:
```

2024-10-15 14:03 UTC, IwonaLanger commented on cmd/image-builder/README.md
> +- if the value is go-template, it will be converted to a valid name. For example, `-tag v{{ .ShortSHA }}-{{ .Date }}` is equal
```suggestion
- If the value is a string, it is used directly as a name. For example,`-tag latest` is equal to `-tag latest=latest`
- If the value is go-template, it is converted to a valid name. For example, `-tag v{{ .ShortSHA }}-{{ .Date }}` is equal
```

2024-10-16 07:51 UTC, Sawthis approved these changes

2024-10-16 15:42 UTC, IwonaLanger approved these changes

2024-10-16 15:43 UTC, merged