Add description of Go internal modules
kyma-project/test-infra pull request #12336
Opened 2024-11-13 10:39 UTC by KacperMalachowski

**Description**

Changes proposed in this pull request:

- Add description of handling go internal modules in ADO backend.

2024-11-14 09:31 UTC, Sawthis requested changes

2024-11-14 09:31 UTC, Sawthis commented on cmd/image-builder/image-builder.md
> +## Access Golang Internal Modules
```suggestion
## Access Golang SAP Internal Modules
```

2024-11-14 09:31 UTC, Sawthis commented on cmd/image-builder/image-builder.md
> +You can use Image Builder to build images that require access to Go internal modules. To use this feature, set the `--use-go-internal-modules=true` flag.
```suggestion
You can use Image Builder to build images that require access to Go SAP internal modules. To use this feature, set the `--use-go-internal-sap-modules=true` flag.
```

2024-11-18 06:58 UTC, IwonaLanger commented on cmd/image-builder/image-builder.md
> +This feature utilize the `go` vendor mechanism by downloading all the dependencies into the `vendor` directory. There is no option to pass custom credentials for fetching the dependencies, the tool h
```suggestion
This feature utilizes the `go` vendor mechanism by downloading all the dependencies into the `vendor` directory. There is no option to pass custom credentials for fetching the dependencies; the tool handles it internally.
```

2024-11-18 07:08 UTC, Sawthis approved these changes

2024-11-18 07:09 UTC, IwonaLanger approved these changes

2024-11-18 07:13 UTC, merged