Component jobs: use new templates
kyma-project/test-infra pull request #3733
Opened 2021-06-07 10:30 UTC by Halamix2

**Description**

Changes proposed in this pull request:

- rework generic component jobs to use new templating

**Related issue(s)**

#3452

2021-06-07 10:30 UTC, Halamix2 commented
/test all

2021-06-07 10:51 UTC, Halamix2 commented
/test all

2021-06-07 11:16 UTC, Halamix2 commented
/test all

2021-06-07 11:19 UTC, Halamix2 commented
/test all

2021-06-07 13:59 UTC, Halamix2 commented
/test all

2021-06-07 14:01 UTC, Halamix2 commented
/test pre-main-test-infra-validate-generated-files

2021-06-07 14:21 UTC, Halamix2 commented
/test all

2021-06-07 15:12 UTC, Halamix2 commented
/test all

2021-06-08 06:54 UTC, Halamix2 commented
/test all

2021-06-16 09:23 UTC, dekiel requested changes

2021-06-16 09:23 UTC, dekiel commented on development/tools/pkg/rendertemplates/genericcomponent.go
> +					if ReleaseMatches(global["nextRelease"], job.jobConfigPre["release_since"], job.jobConfigPre["release_until"]) {
Can we search for release_since and release_until in whole JobConfig not only in jobConfigPre and jobConfigPost? If you want pre and post generate for same set of release which I think is our case, you can set the boundaries in jobConfig to apply for both instead setting them twice for pre and post.

2021-06-16 09:32 UTC, Halamix2 commented on development/tools/cmd/rendertemplates/main.go
> +	//{{ $runIDtrunc := trunc 63 .JobConfig.name}}{{ if hasSuffix "-" $runIDtrunc}}{{ substr 0 (sub ( (len $runIDtrunc) | int ) 1) $runIDtrunc | quote }}{{else}}{{ $runIDtrunc | quote}}{{end}}
Done

2021-06-16 09:35 UTC, Halamix2 commented on development/tools/pkg/rendertemplates/genericcomponent.go
> +		for extraRefIndex := range j.JobConfig["extra_refs"].(map[interface{}]interface{}) {
Linter won't let me use `extraRefIndex, _`

2021-06-16 20:08 UTC, dekiel approved these changes

2021-06-16 20:16 UTC, merged