Busola deployments update check
kyma-project/test-infra pull request #3863
Opened 2021-07-02 08:16 UTC by Sawthis

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-07-02 08:47 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 09:04 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 09:13 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 09:17 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 09:26 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 09:33 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 09:38 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 09:40 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 09:50 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 10:23 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-02 10:28 UTC, Sawthis commented
/test pre-main-test-infra-pjtester

2021-07-05 08:08 UTC, parostatkiem requested changes

2021-07-05 08:08 UTC, parostatkiem commented on templates/data/busola-web-deployment-check-data.yaml
> +                  run_if_changed: "^core/|^core-ui/|^service-catalog-ui/|^components/|^shared/|^package.json"
We don't have the `components` folder anymore

2021-07-05 08:18 UTC, parostatkiem submitted a review, later dismissed

2021-07-05 11:34 UTC, dekiel requested changes

2021-07-05 12:03 UTC, Sawthis commented on templates/data/busola-backend-deployment-check-data.yaml
> +          jobConfig_periodic:
fixed

2021-07-05 12:03 UTC, Sawthis commented on templates/data/busola-web-deployment-check-data.yaml
> +          jobConfig_periodic:
fixed

2021-07-06 10:32 UTC, dekiel approved these changes

2021-07-06 10:33 UTC, merged