External secrets: add readme
kyma-project/test-infra pull request #3931
Opened 2021-07-16 12:18 UTC by Halamix2

**Description**

Changes proposed in this pull request:

- add readme to external secrets syncer
**Related issue(s)**

2021-07-19 09:08 UTC, Halamix2 commented
/hold

2021-07-19 10:02 UTC, mmitoraj reviewed
Please see my comments below. Thank you.

2021-07-19 11:43 UTC, mmitoraj reviewed
Have a look at my suggestions below. Thank you.

2021-07-19 11:43 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +4. Install `external-secrets/kubernetes-external-secrets` Helm chart. Run `helm install -f prow/cluster/resources/external-secrets/values_untrusted.yaml -n external-secrets kubernetes-external-secret
```suggestion
4. Install  the`external-secrets/kubernetes-external-secrets` Helm chart. Run `helm install -f prow/cluster/resources/external-secrets/values_untrusted.yaml -n external-secrets kubernetes-external-secrets external-secrets/kubernetes-external-secrets`.
```

2021-07-19 11:43 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +# Configuration
```suggestion

# Configuration
```

2021-07-19 11:43 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +# Configuration
Please add an empty line above the header.

2021-07-20 06:55 UTC, mmitoraj approved these changes

2021-07-30 10:20 UTC, Halamix2 commented
/retest

2021-08-02 10:36 UTC, mmitoraj requested changes
Hi, I left my comments, please capitalize the word `Secrets` and correct the last section. Thank you.

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +# External secrets
```suggestion
# External Secrets
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +Kubernetes secrets are synchronized with GCP Secret Manager using [Kubernetes External Secrets](https://github.com/external-secrets/kubernetes-external-secrets).
```suggestion
Kubernetes Secrets are synchronized with GCP Secret Manager using [Kubernetes External Secrets](https://github.com/external-secrets/kubernetes-external-secrets).
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +2. Add the `sa-secret-manager-untrusted` secret containing credentials for a GCP service account with permission to access secrets.
```suggestion
2. Add the `sa-secret-manager-untrusted` Secret containing credentials for a GCP service account with permission to access Secrets.
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +Secrets can be stored as text in GCP Secret Manager and be mapped to a Kubernetes secret with one key.
```suggestion
Secrets can be stored as text in GCP Secret Manager and be mapped to a Kubernetes Secret with one key. 
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +Secrets can also be stored as JSON in GCP Secret Manager and be mapped to a Kubernetes secret with multiple keys.
```suggestion
Secrets can also be stored as JSON in GCP Secret Manager and be mapped to a Kubernetes Secret with multiple keys. 
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +External Secrets Checker checks if all External Secrets have synchronized succesfully, and if all Secrets have corresponding External Secrets.
```suggestion
External Secrets Checker checks if all External Secrets synchronized successfully, and if all Secrets have corresponding External Secrets.
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +  name: secretName # name of the k8s external secret and the k8s secret
```suggestion
  name: secretName # name of the k8s external Secret and the k8s Secret
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +    - key: gcp-json-secret # name of the GCP secret
```suggestion
    - key: gcp-json-secret # name of the GCP Secret
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +      name: keyName # key name in the k8s secret
```suggestion
      name: keyName # key name in the k8s Secret
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +      version: latest # version of the GCP secret
```suggestion
      version: latest # version of the GCP Secret
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +      property: keyName # name of the field in the GCP secret JSON, unused for plain values
```suggestion
      property: keyName # name of the field in the GCP Secret JSON, unused for plain values
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +    - key: gcp-json-secret # name of the GCP secret
```suggestion
    - key: gcp-json-secret # name of the GCP Secret
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +      name: anotherKey # key name in the k8s secret
```suggestion
      name: anotherKey # key name in the k8s Secret
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +      version: latest # version of the GCP secret
```suggestion
      version: latest # version of the GCP Secret
```

2021-08-02 10:36 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +      property: anotherKey # name of the field in the GCP secret JSON, unused for plain values
```suggestion
      property: anotherKey # name of the field in the GCP Secret JSON, unused for plain values
```

2021-08-02 10:50 UTC, mmitoraj commented on prow/cluster/resources/external-secrets/README.md
> +It can be installed with the `kubectl apply -f external_secrets_checker_prow.yaml` command.
```suggestion
To install External Secrets Checker run the following command: 

`kubectl apply -f external_secrets_checker_prow.yaml`
```

2021-08-02 10:52 UTC, mmitoraj approved these changes

2021-08-02 14:18 UTC, Halamix2 commented
/hold cancel

2021-08-02 14:19 UTC, adamwalach approved these changes

2021-08-02 14:23 UTC, merged