Prow: update secrets population
kyma-project/test-infra pull request #4045
Opened 2021-08-16 10:42 UTC by Halamix2

**Description**

Changes proposed in this pull request:

- remove references to `sap-kyma-secrets` bucket
- replace `secretspopulator` with External Secrets Syncer
- ...

**Related issue(s)**

2021-08-16 10:42 UTC, Halamix2 commented
/test all

2021-08-16 11:43 UTC, Halamix2 commented
/test all

2021-08-17 13:27 UTC, mmitoraj requested changes

2021-08-17 13:27 UTC, mmitoraj commented on docs/prow/obligatory-security-measures.md
> +All Secret used in the Prow production cluster must be changed every six months. Follow [Prow secret management](./prow-secrets-management.md) to create a new key ring and new Secrets. Then, [Externa
```suggestion
All Secrets used in the Prow production cluster must be changed every six months. Follow the [Prow secret management](./prow-secrets-management.md) guidelines to create a new key ring and new Secrets. Once the key ring and new Secrets are ready, the [External Secrets Syncer](../../prow/workload-cluster/README.md) changes all Secrets in the Prow cluster automatically.
```
The link ->  [External Secrets Syncer](../../prow/workload-cluster/README.md) doesn't point the External Secrets Syncer

2021-08-17 13:27 UTC, mmitoraj commented on docs/prow/obligatory-security-measures.md
> +Change all Secrets that were valid when the person was a project member. Follow [Prow secret management](./prow-secrets-management.md) to create a new key ring and new Secrets. Then, [External Secret
```suggestion
Change all Secrets that were valid when the person was a project member. Follow the [Prow secret management](./prow-secrets-management.md) guidelines to create a new key ring and new Secrets. Once the key ring and new Secrets are ready, the [External Secrets Syncer](../../prow/workload-cluster/README.md) changes all Secrets in the Prow cluster automatically.
```
The link ->  [External Secrets Syncer](../../prow/workload-cluster/README.md) doesn't point the External Secrets Syncer

2021-08-17 13:27 UTC, mmitoraj commented on docs/prow/prow-installation-on-forks.md
> +- **GOOGLE_APPLICATION_CREDENTIALS** is a path to a service account file. This service account requires read access to secretes stored in Secret Manager.
```suggestion
- **GOOGLE_APPLICATION_CREDENTIALS** is a path to a service account file. This service account requires read access to Secrets stored in the Secret Manager.
```

2021-08-18 05:40 UTC, mmitoraj approved these changes

2021-08-18 07:10 UTC, adamwalach approved these changes

2021-08-18 07:11 UTC, merged