[do not merge] test changes to the markdown files
kyma-project/test-infra pull request #4548
Opened 2021-12-09 15:41 UTC by Ressetkk

Testing web hook changes for plugin

/hold

2021-12-09 15:49 UTC, adamwalach requested changes

2021-12-09 15:49 UTC, adamwalach commented on prow/README.md
> +Here are dummy changes
change that :)

2022-01-19 08:06 UTC, klaudiagrz approved these changes
👀

2022-01-19 12:51 UTC, klaudiagrz requested changes
nope

2022-01-19 13:04 UTC, klaudiagrz approved these changes
test

2022-01-19 13:15 UTC, adamwalach approved these changes

2022-01-20 08:09 UTC, klaudiagrz requested changes
🙅

2022-01-20 08:26 UTC, klaudiagrz submitted a review, later dismissed

2022-01-20 10:25 UTC, Ressetkk commented
/shrug

2022-01-20 10:39 UTC, klaudiagrz approved these changes

2022-01-20 10:39 UTC, klaudiagrz requested changes
nope

2022-01-20 12:15 UTC, klaudiagrz approved these changes

2022-01-20 12:16 UTC, klaudiagrz requested changes
nope 🙅

2022-01-21 18:41 UTC, closed without merging