Pin sigstore version
kyma-project/test-infra pull request #4583
Opened 2021-12-16 10:33 UTC by Halamix2

**Description**

Changes proposed in this pull request:

- Pin sigstore version to 1.0.1 due to breaking changes in 1.0.2
- pin cosign to 1.0.1 (can be upgraded to 1.3.1), since 1.4.1 requires sigstore 1.0.2

**Related issue(s)**

2021-12-16 10:59 UTC, dekiel requested changes
If cosign can be upgraded to version 1.3.1 we should use latest possible version.

2021-12-16 11:57 UTC, Ressetkk commented
What are the changes in the cosign that block updating image-syncer codebase then? AFAIK It's the only package that implements cosign. If so then cosign should be updated with the codebase along it.

2021-12-17 12:03 UTC, Halamix2 commented
> What are the changes in the cosign that block updating image-syncer codebase then? AFAIK It's the only package that implements cosign. If so then cosign should be updated with the codebase along it.

Cosign in version 1.3.0 added some braking changes to all functions we're using from these packages, changing abstractions in the `/pkg` packages: https://github.com/sigstore/cosign/blob/main/CHANGELOG.md#enhancements-3

2021-12-23 13:59 UTC, dekiel approved these changes

2021-12-23 14:02 UTC, merged