Go Upgrade - 1.18
kyma-project/test-infra pull request #5161
Opened 2022-03-24 11:43 UTC by ralikio

**Description**

Changes proposed in this pull request:

- Go 1.18 Upgrade

**Related issue(s)**

2022-03-24 13:06 UTC, ralikio commented
/test pre-main-test-infra-image-syncer-dry-run

2022-03-25 09:16 UTC, klaudiagrz approved these changes

2022-03-25 09:20 UTC, Halamix2 requested changes

2022-03-25 09:20 UTC, Halamix2 commented on development/prow-installer/before-commit.sh
> +go install golang.org/x/lint/golint
```suggestion
go install golang.org/x/lint/golint@latest
```

2022-03-25 11:06 UTC, Halamix2 commented
/lgtm
/approve

2022-03-25 11:26 UTC, Ressetkk commented
/lgtm
/approve

2022-03-25 11:26 UTC, Halamix2 approved these changes

2022-03-25 12:22 UTC, klaudiagrz approved these changes

2022-03-25 12:30 UTC, merged