Send notification to Slack on release candidate
kyma-project/test-infra pull request #5194
Opened 2022-03-31 06:56 UTC by Halamix2

**Description**

Changes proposed in this pull request:

- send Slack notification on release candidate cluster creation
- bump `pubsub-gateway` image
- bump Python runtime version

**Related issue(s)**

#4906

2022-03-31 06:56 UTC, Halamix2 commented
/cc @dekiel 
/hold

2022-03-31 07:18 UTC, Halamix2 commented
/unhold

2022-04-01 07:57 UTC, Halamix2 commented
/hold

2022-04-01 09:01 UTC, Halamix2 commented
/unhold

2022-04-01 15:21 UTC, dekiel requested changes

2022-04-01 15:21 UTC, dekiel commented on development/kyma-slack-connector/releaseClusterCreatedFunction/handler.py
> +	print("sending notification to channel: {}".format(slack_channel))
Please add some log message with clustername which message is about. It will be easier for human to understand what was processed

2022-04-01 15:21 UTC, dekiel commented on development/kyma-slack-connector/slackConnectorChart/values/releasecluster.created/stage-values.yaml
> +subscriptionAppName: "mp-sap-slack-connector" #pubsub-connector"
```suggestion
subscriptionAppName: "pubsub-connector"
```

2022-04-01 15:21 UTC, dekiel commented on development/kyma-pubsub-connector/pubsubConnectorChart/values/releasecluster.created/prod-values.yaml
> +targetAppName: "mp-slack-connector"
```suggestion
targetAppName: "pubsub-connector"
```

2022-04-05 06:57 UTC, Halamix2 commented on development/kyma-slack-connector/slackConnectorChart/global-stage-values.yaml
> +  repositoryUrl: "https://github.com/Halamix2/test-infra.git"
These are values for staging

2022-04-05 12:04 UTC, dekiel commented
/lgtm
/approve

2022-04-05 12:05 UTC, merged