Introduce a smoke test for Compass director and ORD service
kyma-project/test-infra pull request #5341
Opened 2022-04-27 12:19 UTC by dzahariev

**Description**

Changes proposed in this pull request:

- Introduce a smoke test for Compass director and ORD service

2022-04-27 12:22 UTC, dzahariev commented on prow/jobs/incubator/compass/compass-ord.yaml
> +postsubmits: # runs on main
Remove post execution.

2022-04-27 12:27 UTC, NickyMateev commented
/ok-to-test

2022-04-27 12:32 UTC, dzahariev commented on prow/scripts/provision-vm-compass-ord.sh
> +
Get the version that is listed in values.yaml for ORD service and checkout the branch for the listed PR there.

2022-04-27 12:34 UTC, NickyMateev commented
/test all

2022-04-27 14:36 UTC, dzahariev commented
/retest-required

2022-04-28 10:08 UTC, desislavaa commented
/test all

2022-04-28 10:14 UTC, desislavaa commented
/test all

2022-04-28 10:33 UTC, desislavaa commented
/test all

2022-04-28 10:40 UTC, desislavaa commented
/test all

2022-04-28 14:05 UTC, desislavaa commented
/test all

2022-04-28 16:04 UTC, desislavaa commented
/test all

2022-04-28 16:54 UTC, NickyMateev commented
/test all

2022-04-28 17:43 UTC, dzahariev commented
/test pre-main-test-infra-validate-generated-files

2022-04-28 17:55 UTC, dzahariev commented
/test all

2022-04-28 20:04 UTC, dzahariev commented
/test all

2022-04-29 06:25 UTC, dzahariev commented
/test all

2022-04-29 06:37 UTC, dzahariev commented
/test all

2022-04-29 07:45 UTC, dzahariev commented
/test all

2022-04-29 08:19 UTC, dzahariev commented
/test all

2022-04-29 08:33 UTC, dzahariev commented
/test all

2022-04-29 08:48 UTC, dzahariev commented
/test all

2022-04-29 09:00 UTC, dzahariev commented
/test all

2022-04-29 09:08 UTC, dzahariev commented
/test all

2022-04-29 09:15 UTC, dzahariev commented
/test all

2022-04-29 09:21 UTC, dzahariev commented
/test all

2022-04-29 09:43 UTC, dzahariev commented
/test all

2022-04-29 10:07 UTC, dzahariev commented
/test all

2022-04-29 10:20 UTC, dzahariev commented
/test all

2022-04-29 10:34 UTC, dzahariev commented
/test all

2022-04-29 10:55 UTC, dzahariev commented
/test all

2022-04-29 11:32 UTC, dzahariev commented
/test all

2022-04-29 12:40 UTC, dzahariev commented
/test all

2022-04-29 12:48 UTC, dzahariev commented
/test all

2022-04-29 12:53 UTC, dzahariev commented
/test all

2022-04-29 13:08 UTC, dzahariev commented
/test all

2022-04-29 13:16 UTC, dzahariev commented
/test all

2022-04-29 13:20 UTC, dzahariev commented
/test all

2022-04-29 13:28 UTC, dzahariev commented
/test all

2022-04-29 13:58 UTC, dzahariev commented
/test all

2022-05-03 11:33 UTC, dzahariev commented
/test all

2022-05-03 11:54 UTC, dzahariev commented
/test all

2022-05-03 15:17 UTC, dzahariev commented
/test all

2022-05-05 14:39 UTC, dzahariev commented
/test all

2022-05-05 15:19 UTC, dzahariev commented
/test all

2022-05-05 15:26 UTC, dzahariev commented
/test all

2022-05-05 15:39 UTC, dzahariev commented
/test all

2022-05-11 11:35 UTC, dzahariev commented
/test all

2022-05-11 11:45 UTC, dzahariev commented
/test all

2022-05-11 11:55 UTC, dzahariev commented
/test all

2022-05-11 12:06 UTC, dzahariev commented
/test all

2022-05-11 12:25 UTC, dzahariev commented
/test all

2022-05-11 12:31 UTC, dzahariev commented
/test all

2022-05-11 12:38 UTC, dzahariev commented
/test all

2022-05-11 12:46 UTC, dzahariev commented
/test all

2022-05-11 13:03 UTC, dzahariev commented
/test all

2022-05-11 13:11 UTC, dzahariev commented
/test all

2022-05-11 14:34 UTC, dzahariev commented
/test all

2022-05-11 14:43 UTC, dzahariev commented
/test all

2022-05-11 15:24 UTC, dzahariev commented
/test all

2022-05-12 04:08 UTC, NickyMateev requested changes

2022-05-12 08:28 UTC, dzahariev commented on prow/scripts/provision-vm-compass-ord.sh
> +cd /home/prow/ && git clone https://github.com/kyma-incubator/ord-service.git && cd ord-service && git checkout "${ORD_PR_COMMIT_HASH}" && cd ..
Not very easy, as the compass need to be in GOPATH, in order to be build and run. 
Let keep it that way.

2022-05-12 08:52 UTC, dzahariev commented
/test all

2022-05-12 09:08 UTC, dzahariev commented
/test all

2022-05-16 10:09 UTC, NickyMateev submitted a review, later dismissed

2022-05-17 08:31 UTC, Halamix2 commented on templates/data/compass-smoke-test-data.yaml
> +            request_mcpu: 50m
```suggestion
            request_cpu: 50m
```

2022-05-17 08:39 UTC, dzahariev commented on templates/data/compass-smoke-test-data.yaml
> +            request_mcpu: 50m
Done

2022-05-17 08:41 UTC, Halamix2 approved these changes

2022-05-17 08:45 UTC, merged