Restore api-gateway pipeline
kyma-project/test-infra pull request #5533
Opened 2022-06-03 13:49 UTC by barchw

**Description**
Restore api-gateway pipeline that was deleted in https://github.com/kyma-project/test-infra/pull/4123

Changes proposed in this pull request:

- Restore the pipeline
- Modify test directory to components/api-gateway

**Related issue(s)**

https://github.com/kyma-project/test-infra/issues/5494
https://github.com/kyma-project/kyma/pull/14491

2022-06-09 07:49 UTC, cnvergence commented on templates/data/kyma-integration-gardener-data.yaml
> +                  run_if_changed: "^((resources/api-gateway\\S+)(\\.[^.][^.][^.]+$|\\.[^.][^dD]$|\\.[^mM][^.]$|\\.[^.]$|/[^.]+$))"
I think we can add the same to post job
```
  run_if_changed: "^((tests/components/api-gateway\\S+|resources/api-gateway\\S+)(\\.[^.][^.][^.]+$|\\.[^.][^dD]$|\\.[^mM][^.]$|\\.[^.]$|/[^.]+$))"
env:
    API_GATEWAY_INTEGRATION: "true"
    TEST_ORY_IMAGE: "eu.gcr.io/kyma-project/incubator/test-hydra-login-consent:d6e6d3bc"
```

2022-06-09 09:30 UTC, barchw commented on templates/data/kyma-integration-gardener-data.yaml
> +                  run_if_changed: "^((resources/api-gateway\\S+)(\\.[^.][^.][^.]+$|\\.[^.][^dD]$|\\.[^mM][^.]$|\\.[^.]$|/[^.]+$))"
Added this change

2022-06-09 09:42 UTC, strekm requested changes

2022-06-09 11:01 UTC, strekm approved these changes

2022-06-09 11:28 UTC, cnvergence submitted a review, later dismissed

2022-06-10 10:24 UTC, dekiel approved these changes

2022-06-10 11:00 UTC, dekiel approved these changes

2022-06-10 11:01 UTC, cnvergence approved these changes

2022-06-10 11:20 UTC, grego952 approved these changes

2022-06-10 11:27 UTC, merged