Fix compass benchmark job
kyma-project/test-infra pull request #5938
Opened 2022-08-30 12:54 UTC by PetarTodorovv

**Description**
With some recent changes the benchmark job is not adapter and now it's failing. The missing `compass-postgresql` secret is not created

Changes proposed in this pull request:
- Install postgresql charts before compass installation

**Related issue(s)**
- https://github.com/kyma-incubator/compass/pull/2568

2022-08-30 12:57 UTC, PetarTodorovv commented
/test all

2022-08-31 06:34 UTC, PetarTodorovv commented
/test all

2022-08-31 09:59 UTC, PetarTodorovv commented
/test all

2022-09-09 10:08 UTC, dzahariev approved these changes

2022-09-09 10:09 UTC, dzahariev requested changes

2022-09-09 10:09 UTC, dzahariev commented on vpath/pjtester.yaml
> +      prNumber: 2596
2616

2022-09-09 10:23 UTC, PetarTodorovv commented
/test all

2022-09-09 10:51 UTC, PetarTodorovv commented
/test all

2022-09-09 13:26 UTC, dzahariev commented
/test all

2022-09-12 04:41 UTC, PetarTodorovv commented
/test all

2022-09-12 10:28 UTC, dzahariev commented
/test all

2022-09-12 11:07 UTC, dzahariev commented
/test all

2022-09-12 12:33 UTC, dzahariev commented
/test all

2022-09-13 06:39 UTC, dzahariev commented
/test all

2022-09-13 07:27 UTC, dzahariev commented
/test all

2022-09-13 08:10 UTC, dzahariev commented
/test all

2022-09-13 09:08 UTC, dzahariev commented
/test all

2022-09-13 10:17 UTC, dzahariev commented
/test all

2022-09-13 10:44 UTC, dzahariev commented
/test all

2022-09-13 10:52 UTC, dzahariev commented
/test all

2022-09-13 11:15 UTC, dzahariev commented
/test all

2022-09-15 11:26 UTC, PetarTodorovv commented
/test all

2022-09-15 11:56 UTC, PetarTodorovv commented
/test all

2022-09-15 12:32 UTC, PetarTodorovv commented
/test all

2022-09-15 12:59 UTC, PetarTodorovv commented
/test all

2022-09-15 13:23 UTC, PetarTodorovv commented
/test all

2022-09-15 13:41 UTC, PetarTodorovv commented
/test all

2022-09-15 14:35 UTC, PetarTodorovv commented
/test all

2022-09-16 06:47 UTC, PetarTodorovv commented
/test all

2022-09-16 08:31 UTC, PetarTodorovv commented
/test all

2022-09-16 08:32 UTC, PetarTodorovv commented
/test all

2022-09-16 09:02 UTC, PetarTodorovv commented
/test all

2022-09-16 09:26 UTC, PetarTodorovv commented
/test all

2022-09-16 09:53 UTC, PetarTodorovv commented
/test all

2022-09-16 10:01 UTC, PetarTodorovv commented
/test all

2022-09-16 11:39 UTC, ivantenevvasilev approved these changes

2022-09-16 12:11 UTC, DimitarPetrov approved these changes

2022-09-16 12:17 UTC, merged