Add SA cleaner
kyma-project/test-infra pull request #5964
Opened 2022-09-06 10:47 UTC by Halamix2

**Description**

Changes proposed in this pull request:

- Add cleaner for service-accounts secrets in Secret Manager
- ...
- ...

**Related issue(s)**

- #5748

2022-09-06 10:47 UTC, Halamix2 commented
/retest

2022-09-06 10:53 UTC, Halamix2 commented
/retest

2022-09-06 11:07 UTC, Halamix2 commented
/retest

2022-09-07 08:24 UTC, Halamix2 commented
/retest

2022-09-07 08:41 UTC, Halamix2 commented
/retest

2022-09-12 06:23 UTC, Halamix2 commented
/retest

2022-09-12 08:37 UTC, Halamix2 commented
/retest

2022-09-12 11:25 UTC, Halamix2 commented
/retest

2022-09-12 12:45 UTC, Halamix2 commented
/retest

2022-09-12 12:48 UTC, Halamix2 commented
/retest

2022-09-12 12:55 UTC, Halamix2 commented
/retest

2022-09-13 07:12 UTC, Halamix2 commented
/retest

2022-09-13 07:27 UTC, Halamix2 commented
/retest

2022-09-13 07:53 UTC, Halamix2 commented
/retest

2022-09-13 07:55 UTC, Halamix2 commented
/retest

2022-09-13 08:05 UTC, Halamix2 commented
/retest

2022-09-13 09:51 UTC, Halamix2 commented
/retest

2022-09-13 10:51 UTC, Halamix2 commented
/retest

2022-09-13 11:36 UTC, Halamix2 commented
/retest

2022-09-14 07:19 UTC, Halamix2 commented
/retest

2022-10-05 06:04 UTC, Halamix2 commented
/retest

2022-10-06 08:59 UTC, Sawthis requested changes

2022-10-10 07:17 UTC, Halamix2 commented on development/gcp/pkg/secretmanager/service.go
> +		// TODO support paging
Done

2022-10-10 07:33 UTC, Sawthis approved these changes
Approved

2022-10-10 07:33 UTC, merged