Reuse VMs as part of compass-integration jobs
kyma-project/test-infra pull request #6078
Opened 2022-09-27 07:57 UTC by dzahariev

**Description**
Reuse VMs as part of compass-integration jobs

Changes proposed in this pull request:
- Add PJTester and increase tracing
- Introduce pre and post jobs
- Refactor job scripts

Replaces https://github.com/kyma-project/test-infra/pull/6045

2022-10-02 00:06 UTC, NickyMateev commented on vpath/pjtester.yaml
> +pjNames:
Remove this file before merge

2022-10-05 17:13 UTC, NickyMateev commented on prow/scripts/provision-vm-compass.sh
> +PROVISIONING_PASS="no"
Can you put a more meaningful name than `PROVISIONING_PASS` as it doesn't tell me anything just looking at it AND/OR add a comment explaining it like with the `RECYCLE_VM`.

2022-10-07 09:10 UTC, PetarTodorovv requested changes

2022-10-10 14:26 UTC, dzahariev commented on templates/data/compass-integration-with-dump-clean-data.yaml
> +              - "compass-integration-test-with-dump"
Exactly this I the reason I make it to accept parameters. To reuse the script in both jobs. 
If we make a script to work without parameters and to cleanup all VMs - one of the jobs will cleanup the other job VM and will kill the tests that are executed inside. Faster job will always finish and will kill the VM of both jobs.

2022-10-10 14:28 UTC, dzahariev commented
/test all

2022-10-11 06:23 UTC, dzahariev commented on prow/scripts/clean-vm-compass.sh
> +    export JOB_NAME_PATTERN="(^pre-main-compass-integration$)|(^pre-main-compass-integration-no-dump$)"
The post jobs are also scheduled with PJTester.

2022-10-11 06:44 UTC, dzahariev commented on prow/scripts/provision-vm-compass.sh
> +    log::info "VM will be recycled and reused to execute validaiton of next commit in this PR: ${SUFFIX}"
The job is executed either on PR or on main branch. The possible suffixes here are either "PR-XXXX" or "main".

2022-10-11 07:27 UTC, dzahariev commented
/test all

2022-10-11 13:56 UTC, dzahariev commented
/test pre-main-test-infra-lint

2022-10-11 14:30 UTC, dzahariev commented
/test all

2022-10-11 14:48 UTC, dzahariev commented
/test all

2022-10-12 05:02 UTC, dzahariev commented
/test all

2022-10-12 06:58 UTC, dzahariev commented
/test all

2022-10-12 08:52 UTC, dzahariev commented
/test all

2022-10-12 09:21 UTC, dzahariev commented
/test all

2022-10-12 10:48 UTC, dzahariev commented
/test all

2022-10-12 14:47 UTC, PetarTodorovv approved these changes

2022-10-12 14:52 UTC, Ressetkk approved these changes

2022-10-12 14:52 UTC, merged