Fixk3d upgrade tests
kyma-project/test-infra pull request #6638
Opened 2022-12-28 12:55 UTC by jeremyharisch

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-12-28 12:55 UTC, jeremyharisch commented
/hold

2022-12-29 15:28 UTC, tobiscr commented on prow/scripts/lib/gardener/azure.sh
> +                \?)
Would recommend to use `*)` as fallback

2022-12-30 08:59 UTC, tobiscr requested changes

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/lib/utils.sh
> +  log::info "### GET KYMA FAST INTEGRATION DIR"
```suggestion
```

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/lib/utils.sh
> +  log::info "### Kyma Fast-integration-Test-Directory $kymaDirectory"
```suggestion
```

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/lib/utils.sh
> +  echo "$kymaDirectory"
```suggestion
  echo -n "$kymaDirectory"
```

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-minor-versions.sh
> +  log::info "### test directory: $kyma2_install_dir/tests/fast-integration"
```suggestion
  log::info "### test directory: '$kyma2_install_dir/tests/fast-integration'"
```

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/lib/gardener/aws.sh
> +    log::info "Switching directory to $kymaDirectory"
```suggestion
    log::info "Switching directory to '$kymaDirectory'"
```

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/lib/gardener/aws.sh
> +    log::info "Switching directory to $kymaDirectory"
```suggestion
    log::info "Switching directory to '$kymaDirectory'"
```

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/lib/gardener/azure.sh
> +    log::info "Switching directory to $kymaDirectory"
```suggestion
    log::info "Switching directory to '$kymaDirectory'"
```

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/lib/gardener/azure.sh
> +    log::info "Switching directory to $kymaDirectory"
```suggestion
    log::info "Switching directory to '$kymaDirectory'"
```

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/lib/gardener/gcp.sh
> +    log::info "Switching directory to $kymaDirectory"
```suggestion
    log::info "Switching directory to '$kymaDirectory'"
```

2022-12-30 08:59 UTC, tobiscr commented on prow/scripts/lib/gardener/gcp.sh
> +    log::info "Switching directory to $kymaDirectory"
```suggestion
    log::info "Switching directory to '$kymaDirectory'"
```

2022-12-30 09:26 UTC, tobiscr requested changes

2022-12-30 09:26 UTC, tobiscr commented on prow/scripts/lib/gardener/azure.sh
> +    kymaDirectory="${utils::get_kyma_fast_integration_dir $@}"
```suggestion
    kymaDirectory="$(utils::get_kyma_fast_integration_dir $@)"
```

2022-12-30 09:26 UTC, tobiscr commented on prow/scripts/lib/gardener/azure.sh
> +    kymaDirectory="${utils::get_kyma_fast_integration_dir $@}"
```suggestion
    kymaDirectory="$(utils::get_kyma_fast_integration_dir $@)"
```

2022-12-30 09:26 UTC, tobiscr commented on prow/scripts/lib/gardener/gcp.sh
> +    kymaDirectory="${utils::get_kyma_fast_integration_dir $@}"
```suggestion
    kymaDirectory="$(utils::get_kyma_fast_integration_dir $@)"
```

2022-12-30 09:26 UTC, tobiscr commented on prow/scripts/lib/gardener/gcp.sh
> +    kymaDirectory="${utils::get_kyma_fast_integration_dir $@}"
```suggestion
    kymaDirectory="$(utils::get_kyma_fast_integration_dir $@)"
```

2022-12-30 09:26 UTC, tobiscr commented on prow/scripts/lib/gardener/aws.sh
> +    kymaDirectory="${utils::get_kyma_fast_integration_dir $@}"
```suggestion
    kymaDirectory="$(utils::get_kyma_fast_integration_dir $@)"
```

2022-12-30 09:26 UTC, tobiscr commented on prow/scripts/lib/gardener/aws.sh
> +    kymaDirectory="${utils::get_kyma_fast_integration_dir $@}"
```suggestion
    kymaDirectory="$(utils::get_kyma_fast_integration_dir $@)"
```

2022-12-30 09:27 UTC, tobiscr submitted a review, later dismissed

2022-12-30 09:27 UTC, tobiscr commented on prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-minor-versions.sh
> +    gardener::pre_upgrade_test_fast_integration_kyma -d "$kyma2_install_dir"/tests/fast-integration
```suggestion
    gardener::pre_upgrade_test_fast_integration_kyma -d "${kyma2_install_dir}/tests/fast-integration"
```

2022-12-30 09:27 UTC, tobiscr commented on prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-to-main.sh
> +gardener::pre_upgrade_test_fast_integration_kyma -d kyma2/"$KYMA_SOURCE"/tests/fast-integration
```suggestion
gardener::pre_upgrade_test_fast_integration_kyma -d "kyma2/${KYMA_SOURCE}/tests/fast-integration"
```

2022-12-30 12:21 UTC, jeremyharisch commented
/unhold

2022-12-30 12:23 UTC, ruanxin commented on prow/scripts/lib/gardener/gcp.sh
> +    log::info "Running pre-upgrade Kyma Fast Integration tests - GCP"
```suggestion
    log::info "Running post-upgrade Kyma Fast Integration tests - GCP"
```

2022-12-30 12:27 UTC, ruanxin approved these changes

2022-12-30 12:50 UTC, tobiscr approved these changes

2022-12-30 13:12 UTC, adityabhatia approved these changes

2022-12-30 13:17 UTC, Ressetkk approved these changes

2022-12-30 13:19 UTC, merged