WIP: Kyma dashboard
kyma-project/test-infra pull request #6639
Opened 2022-12-28 13:37 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-12-28 13:38 UTC, mrCherry97 commented
/test all

2022-12-28 13:42 UTC, mrCherry97 commented
/test pull-kyma-dashboard-pjtester

2022-12-28 13:42 UTC, mrCherry97 commented
/test pull-test-infra-pjtester

2022-12-28 13:46 UTC, mrCherry97 commented
/test pull-test-infra-pjtester

2022-12-28 13:51 UTC, mrCherry97 commented
/test pull-test-infra-pjtester

2022-12-28 13:57 UTC, mrCherry97 commented
/test pull-test-infra-pjtester

2022-12-28 14:54 UTC, mrCherry97 commented
/test pull-test-infra-pjtester

2022-12-30 09:56 UTC, mrCherry97 commented
/hold

2022-12-30 09:56 UTC, mrCherry97 commented
This is ready for review, but before merging still waiting for review: https://github.com/kyma-project/kyma-dashboard/pull/56

2023-01-03 08:35 UTC, mrCherry97 commented
PR for Kyma-dashboard is merged so this PR is ready for review and merge.

2023-01-03 09:23 UTC, halamix2 requested changes

2023-01-03 09:23 UTC, halamix2 commented on templates/data/kyma-dashboard-test.yaml
> +                  run_if_changed: "/"
You can replace `run_if_changed: "/"` with
```suggestion
                  always_run: true
```

2023-01-03 09:28 UTC, halamix2 commented
/retest

2023-01-03 09:32 UTC, halamix2 approved these changes

2023-01-03 09:40 UTC, merged