Switch SAs to workload identity
kyma-project/test-infra pull request #7393
Opened 2023-03-31 11:25 UTC by kasiakepka

**Description**

Changes proposed in this pull request:

- Switch SAs to workload identity: replace presets with service account definition.
[sa-prow-deploy@sap-kyma-prow.iam.gserviceaccount.com](mailto:sa-prow-deploy@sap-kyma-prow.iam.gserviceaccount.com) 
[sa-prow-job-resource-cleaners@sap-kyma-prow.iam.gserviceaccount.com](mailto:sa-prow-job-resource-cleaners@sap-kyma-prow.iam.gserviceaccount.com)
[sa-prowjob-gcp-logging-client@sap-kyma-prow.iam.gserviceaccount.com](mailto:sa-prowjob-gcp-logging-client@sap-kyma-prow.iam.gserviceaccount.com)
[sa-secret-update@sap-kyma-prow.iam.gserviceaccount.com](mailto:sa-secret-update@sap-kyma-prow.iam.gserviceaccount.com) 

- Add sa-kyma-github-issues to external secrets

2023-04-03 14:12 UTC, dekiel commented on templates/data/secret-rotation-data.yaml
A service-account parameter is expecting a path to the json key file. Values you provided looks suspicious for me. I think they are not correct locations for this file.

See docs for the tool: https://github.com/kyma-project/test-infra/blob/694650155d5870d925a78f7ebb5b9f81df0995ea/development/gardener-rotate/README.md

2023-04-03 14:13 UTC, dekiel requested changes
Please check value provided to the gardener-rotate parameters.

2023-04-11 11:30 UTC, kasiakepka commented
@dekiel all changes made to `sa-secret-update` and `preset-sa-secret-update` were reverted.

2023-04-13 06:56 UTC, dekiel approved these changes
Please create a follow up issue to make gardener rotate tool able to work with workload identity setup. The tool should not relay on file with gcp service account credentials. It should be able to work with GOOGLE_APPLICATION_CREDENTIALS variable as far I remember.

2023-04-13 07:53 UTC, IwonaLanger approved these changes

2023-04-13 07:58 UTC, merged