Initial rework of images
kyma-project/test-infra pull request #7495
Opened 2023-04-18 11:02 UTC by Ressetkk

Initial configuration for new test-infra images

* Alpine-based
* rootless (minus k3d image)
* contain only required binaries
* have least number of layers

#6793

2023-04-21 13:42 UTC, KacperMalachowski requested changes
Also, please verify if README files for e2e-garden and e2e-gcloud shouldn't be also included in this PR.

2023-04-21 13:42 UTC, KacperMalachowski commented on images/e2e-dind-k3d/Dockerfile
> +    rm install.sh
```suggestion
RUN curl -Lso install.sh https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh && \
    chmod +x ./install.sh &&\
    TAG=${K3D_VERSION} ./install.sh &&\
    rm install.sh
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/README.md
> +This directory contains images that can be used as runtime images for all ProwJobs in Kyma's prow instance.
```suggestion
This directory contains images that can be used as runtime images for all ProwJobs in Kyma's Prow Instance.
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/README.md
> +Please refer to the README.md files in the image subdirectories for more information.
```suggestion
Refer to the README.md files in the image subdirectories for more information.
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/README.md
> +To add additional applications into the images, open a PR with changes. Keep in mind the following recommendations:
```suggestion
To add additional applications into the images, open a PR with changes. Follow these recommendations:
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/README.md
> +* Build binaries in separate stage then copy resulting binary into final image to ensure images are small and contain the least number of layers
```suggestion
* Build binaries in a separate stage, then copy the resulting binary into the final image to ensure images are small and contain the least number of layers
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/README.md
> +* Link binary to specific version, so it's easier to update it when needed
```suggestion
* Link the binary to a specific version so that it's easier to update when necessary 
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/README.md
> +* Always build from source to ensure compiler vulnerabilities do not affect resulting binary
```suggestion
* Always build from a source to ensure compiler vulnerabilities do not affect the resulting binary
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/buildpack-go/README.md
> +It's based on official Alpine-based [`golang`](https://hub.docker.com/_/golang) image.
```suggestion
This image contains a common toolchain for building and running Go-based applications and container images.
It's based on the official Alpine-based [`golang`](https://hub.docker.com/_/golang) image.
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/e2e-dind-k3d/README.md
> +K3d runs in docker-in-docker mode. Image is alpine-based.
```suggestion
K3d runs in docker-in-docker mode. The image is Alpine-based.
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/e2e-dind-k3d/README.md
> +Usage of this image is restricted only for running K3d/kind workloads for testing.
```suggestion
The usage of this image is restricted only to running K3d/kind workloads for testing.
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/e2e-dind-k3d/README.md
> +1. Use `securityContext: privileged: true` for this image to be running correctly.
```suggestion
1. Use `securityContext: privileged: true` for this image to run correctly.
```

2023-04-26 06:50 UTC, IwonaLanger commented on images/e2e-dind-k3d/README.md
> +2. Do not define `command` directive in ProwJob or Pod definition. If you have to do it, use `/init.sh` as a value.
```suggestion
2. Do not define the `command` directive in ProwJob or Pod definition. If you have to do it, use `/init.sh` as a value.
```

2023-04-26 06:50 UTC, IwonaLanger commented on prow/images/README.md
> +> DEPRECATED: Use [/images](../../images) directory instead.
```suggestion
> DEPRECATED: Use the [`images`](../../images) directory instead.
```

2023-05-02 13:08 UTC, Ressetkk commented
Readme's will be added in the follow-up PRs

2023-05-04 08:20 UTC, KacperMalachowski submitted a review, later dismissed

2023-05-08 13:58 UTC, IwonaLanger approved these changes

2023-05-09 07:42 UTC, KacperMalachowski approved these changes

2023-05-09 07:45 UTC, merged