Add small ProwJob ownership validation test
kyma-project/test-infra pull request #7522
Opened 2023-04-24 14:29 UTC by Ressetkk

/kind feature

As there is a small overhead with ProwJobs this PR provides small metadata check-up where it loads all ProwJobs,
Checks if they contain 2 annotations:
* `owner` - Person/Team responsible for the Job
* `description` - Small information about the purpose of the Job

For now I assumed the current configuration:
* Test works with unit-test-go ProwJob, so no need to add additional ProwJob
* Assumes all ProwJobs are in single repo - TO BE ALIGNED IN THE FUTURE WITH INREPOCONFIG
* Test is optional for now but reports if there are problems in the test. `pull-unit-test-go` should be checked during review
* Directory naming follows go default project layout https://github.com/golang-standards/project-layout/tree/master/test 

Additionally enabled verbose output for tests, so we get information in logs

**Related issue(s)**

#5585

2023-04-24 21:49 UTC, dekiel requested changes
Please extend existing solution for such tests.
https://github.com/kyma-project/test-infra/tree/main/development/prow/pjconfigtests
It already support inrepo config.
It already has a prowjobs defined.

2023-04-25 07:29 UTC, Ressetkk commented
then maybe we should move it to `tests/` then?

2023-04-25 07:59 UTC, Ressetkk commented
Also is there any documentation about adding new checks? I'm not sure how I can integrate this use-case and define it to be executed, but not fail the test.

2023-04-25 09:05 UTC, dekiel commented
> maybe we should move it to `test/` then?

Moving existing solution is not a subject of this PR. We should decide on move, when make an agreement about test-infra structure.

2023-04-25 09:08 UTC, dekiel commented
> Also is there any documentation about adding new checks? I'm not sure how I can integrate this use-case and define it to be executed, but not fail the test.

The solution use a ginkgo framework and gomega matching library.
Documentation for both.
https://onsi.github.io/ginkgo/#top
https://onsi.github.io/gomega/

GInkgo and gomega are compatible and integrated with go test. You can use them together.

2023-04-25 09:29 UTC, dekiel commented
Try to add new `It` block, with calls to `checkRequiredAnnotations` function. By adding `-v` to ginkgo command you will get all output for all steps. It think you are doing the same with go test. See details about logging in ginkgo https://onsi.github.io/ginkgo/#logging-output

2023-04-25 11:03 UTC, dekiel commented
@Ressetkk take a look on section about custom reporting and attaching data to reports.

https://onsi.github.io/ginkgo/#attaching-data-to-reports
https://onsi.github.io/ginkgo/#reporting-nodes---reportaftereach-and-reportbeforeeach

This looks like a way of adding more data to the result without need to run ginkgo in verbose mode.

2023-05-02 11:01 UTC, Ressetkk commented
/close

2023-05-02 11:01 UTC, closed without merging