Goat projects prow run on code changes only
kyma-project/test-infra pull request #7693
Opened 2023-05-12 09:14 UTC by videlov

**Description**

Changes proposed in this pull request:

- Run prow jobs for GOAT projects only on selected paths (exclude Docs/Perf tests etc.)

**Related issue(s)**

2023-05-12 10:28 UTC, Ressetkk commented
I don't know if you are aware, but Prow also supports directive `skip_if_only_changed`. You can use that to simplify the regex overall. https://docs.prow.k8s.io/docs/jobs/#triggering-jobs-based-on-changes

2023-05-12 10:55 UTC, videlov commented
> I don't know if you are aware, but Prow also supports directive `skip_if_only_changed`. You can use that to simplify the regex overall. https://docs.prow.k8s.io/docs/jobs/#triggering-jobs-based-on-changes

Ah cool, I was doing negation regex at first, this could be better with `skip_if_only_changed`. Thx will adapt it.

2023-05-12 12:08 UTC, videlov commented
@Ressetkk `make jobs-definitions` did not render `skip_if_only_changed`, could you take a look?

2023-05-12 12:44 UTC, barchw requested changes

2023-05-12 12:44 UTC, barchw commented on templates/data/api-gateway-validation.yaml
>                    always_run: true
Shouldn't always run be removed?
```suggestion
```

2023-05-12 14:01 UTC, Ressetkk commented
> @Ressetkk `make jobs-definitions` did not render `skip_if_only_changed`, could you take a look?

Unfortunately, you will have to add this field into generic.tmpl. The same way as run_if_changed

2023-05-15 07:17 UTC, Ressetkk approved these changes
LGTM

2023-05-15 08:29 UTC, merged