Add Terraform config for opa gatekeeper constraints
kyma-project/test-infra pull request #7702
Opened 2023-05-16 12:05 UTC by halamix2

**Description**

Changes proposed in this pull request:

- Add Terraform config for opa gatekeeper constraints
- Add prowjobs for automatically applying the config

**Related issue(s)**

/area ci
/kind feature
/retest

2023-05-17 10:51 UTC, halamix2 commented
/retest

2023-05-23 10:55 UTC, halamix2 commented
/retest

2023-05-23 11:00 UTC, halamix2 commented
/cc @dekiel

2023-05-23 11:57 UTC, dekiel requested changes
Please remove dummy files.
Please add description to all variables. This is a best practice recommended in Terraform documentation.

2023-05-23 11:57 UTC, dekiel commented on opa/terraform/modules/constraints/variables.tf
> +  description = "Path to the constraints directory."
These list variables can hold multiple paths.

```suggestion
variable "constraint_templates_path" {
  type        = list(string)
  description = "Paths to the constraint templates directories."
}

variable "constraints_path" {
  type        = list(string)
  description = "Paths to the constraints directories."
```

2023-05-24 10:21 UTC, halamix2 commented on configs/terraform/environments/prod/output.tf
> +  sensitive = true
It now is, after changes to how we handle YAML files

2023-05-24 10:25 UTC, halamix2 commented on opa/terraform/modules/constraints/variables.tf
> +  description = "Path to the constraints directory."
Done

2023-05-24 10:27 UTC, halamix2 commented
- TF plan should succeed after #7750 is merged

2023-05-24 10:27 UTC, halamix2 commented
/retest

2023-05-24 11:20 UTC, halamix2 commented
/retest

2023-05-24 16:07 UTC, dekiel commented
Wait with merge till terraform-executor prowjob will be fixed in #7755 
/hold

2023-05-25 12:51 UTC, dekiel submitted a review, later dismissed

2023-05-25 14:16 UTC, dekiel approved these changes

2023-05-25 14:27 UTC, dekiel commented
/override pull-build-image-image-detector

2023-05-25 14:29 UTC, merged