Add label and change img of istio build module prow job
kyma-project/test-infra pull request #8089
Opened 2023-07-07 12:24 UTC by kolodziejczak

2023-07-07 12:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/test-infra?pullRequest=8089) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/test-infra?pullRequest=8089) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/test-infra?pullRequest=8089) it.</sub>

2023-07-07 14:31 UTC, Ressetkk submitted a review, later dismissed

2023-07-10 06:54 UTC, barchw approved these changes

2023-07-10 07:10 UTC, barchw requested changes
Maybe we should adjust all images to the new registry? https://github.com/kyma-project/test-infra/blob/7aaf0f5e3619d8499b8e9a20bcbd6c894c3c64bb/prow/jobs/istio/istio-manager.yaml#L26

2023-07-10 07:24 UTC, kolodziejczak commented
/retest

2023-07-10 09:23 UTC, barchw approved these changes

2023-07-10 09:47 UTC, Ressetkk approved these changes

2023-07-10 09:49 UTC, merged