Add a job to execute the Eventing tests with the eventingWebhookAuth flag enabled
kyma-project/test-infra pull request #8093
Opened 2023-07-07 15:18 UTC by marcobebway

**Description**

Create a job to execute the Eventing tests with the auth manager flag switched on.

**Related issue(s)**

- https://github.com/kyma-project/kyma/issues/17797

2023-07-07 15:21 UTC, marcobebway commented
/test pre-main-test-infra-pjtester

2023-07-07 15:22 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-12 13:16 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-12 13:27 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-12 13:49 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 07:54 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 08:28 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 09:47 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 10:16 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 10:18 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 10:25 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 10:29 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 10:51 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 11:13 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 12:15 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-13 13:03 UTC, mfaizanse submitted a review, later dismissed

2023-07-14 08:47 UTC, marcobebway commented
/retest

2023-07-14 08:56 UTC, Ressetkk requested changes
The script needs to go. I cannot accept PR with a new script, especially since we work to remove the dependency to test-infra from ProwJobs.

2023-07-14 08:56 UTC, Ressetkk commented on prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
> +        preset-kyma-eventing-auth-ias-creds: "true"
Please, check if these presets are needed.

2023-07-14 08:56 UTC, Ressetkk commented on prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
> +              - "/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/cluster-integration/kyma-integration-gardener-eventing-with-auth-manager.sh"
We stopped allowing adding new copy-pasted scripts. Please consider moving it away to your target repository, or write your own script specifically meant to reflect the actions you need to do. That also includes creating gardener cluster and installing kyma.

2023-07-14 08:56 UTC, Ressetkk commented on prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
> +          base_ref: main
If you remove the script from test-infra you will be able to remove extra_refs pointing to this repo.

2023-07-14 08:56 UTC, Ressetkk commented on prow/jobs/kyma/kyma-integration-gardener-eventing.yaml
> +      path_alias: github.com/kyma-project/kyma
You don't need this field. It's already not needed by Prow.

2023-07-14 11:08 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-14 11:33 UTC, marcobebway commented
/test pull-test-infra-pjtester

2023-07-14 12:00 UTC, marcobebway commented
> The script needs to go. I cannot accept PR with a new script, especially since we work to remove the dependency to test-infra from ProwJobs.

As agreed, reused the same script in both prow jobs.

2023-07-14 13:44 UTC, Ressetkk approved these changes

2023-07-14 13:54 UTC, merged