Add DNS cleaner to Terraform
kyma-project/test-infra pull request #8227
Opened 2023-07-20 08:08 UTC by Sawthis

**Description**

Changes proposed in this pull request:

- Add DNS cleaner to Terraform
- Remove not used dnscleaner app

**Related issue(s)**

https://github.com/kyma-project/test-infra/issues/7609

2023-07-20 09:00 UTC, Sawthis commented
/area ci
/kind feature

2023-07-20 09:10 UTC, dekiel requested changes
Please add comments for which application this config exist and which workload is using it. A link to the cleaner code etc.

2023-07-20 09:10 UTC, dekiel commented on configs/terraform/environments/prod/dns-cleaner.tf
> +  display_name = "sa_gke_kyma_integration"
```suggestion
  account_id   = "sa-gke-kyma-integration@sap-kyma-prow.iam.gserviceaccount.com"
  display_name = "sa-gke-kyma-integration@sap-kyma-prow.iam.gserviceaccount.com"
```

You can't use underscore for sa names. See terraform plan error.

```
Error: "account_id" ("sa_gke_kyma_integration@sap-kyma-prow.iam.gserviceaccount.com") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
```

2023-07-20 09:10 UTC, dekiel commented on configs/terraform/environments/prod/dns-cleaner.tf
> +resource "google_project_iam_binding" "view_container_analysis_ccurrences" {
The resource name sounds to generic. If another identity will need to get same IAM role assigned we will have to use different resource name than `view_container_analysis_ccurrences`. The name of resource should be more specific and provide more context. Maybe something like.

```suggestion
resource "google_project_iam_binding" "dns_cleaner_view_container_analysis_occurrences" {
```

This is the same for bindings of `dns_reader` and `bucket_get` roles.

2023-07-21 07:06 UTC, Sawthis commented
/test all

2023-07-21 09:15 UTC, Sawthis commented
/retest

2023-07-21 11:27 UTC, dekiel approved these changes

2023-07-21 11:48 UTC, IwonaLanger approved these changes

2023-07-21 11:56 UTC, merged