Artifact Registry in a specified project with dedicated provider
kyma-project/test-infra pull request #8769
Opened 2023-08-23 14:51 UTC by the1bit

According to https://github.tools.sap/kyma/backlog/issues/4079 we applied a solution. (PR: https://github.com/kyma-project/test-infra/pull/8479)

Then we realised on 2023-08-10: Due to test-infra basic config, the modules-internal Artifact Registry has been created in wrong project.

Right project: **kyma-project**
Wrong (current) project: **sap-kyma-prow**

Changes proposed in this pull request:

- `immutable_artifact_registry` was renamed to `artifact_registry_immutable_tags`
- Some document related changes
- The entire solution uses a dedicated provider

```yaml
provider "google" {
  alias   = "artifact_registry_gcp"
  project = var.artifact_registry_gcp_project_id
  region  = var.artifact_registry_gcp_region
}
```

What does this improvements mean?
- You can create multiple artifact registry in a dedicated project.
- You cannot create multiple artifact registries in multiple project.
- The project where you can create artifact registries, could be different than the project where the prow execute the terraform solution.

**Related issue(s)**

- https://github.tools.sap/kyma/backlog/issues/4079 
- https://github.com/kyma-project/test-infra/pull/8479

2023-08-24 09:14 UTC, Ressetkk commented
/cc dekiel
/uncc

2023-08-25 10:00 UTC, dekiel requested changes
In the description of PR you wrote.

> You cannot create multiple artifact registries in multiple project.

I think with current module you can use multiple providers to create registries in multiple projects and use `for_each` to create multiple registries in any project. That means there is no limitation you mentioned.

2023-08-28 06:38 UTC, IwonaLanger commented on development/secrets-rotator/cloud-run/service-account-keys-cleaner/README.md
> +ServiceAccountKeysCleaner is deployed to Cloud Run applying Terraform config stored in [./terraform directory](../../../../configs/terraform). `terraform apply` runs automatically on every PR changin
```suggestion
ServiceAccountKeysCleaner is deployed to Cloud Run applying Terraform config stored in [`./terraform` directory](../../../../configs/terraform). `terraform apply` runs automatically on every PR changing Terraform `.tf` files belonging to the application.
```

2023-08-28 06:38 UTC, IwonaLanger commented on development/secrets-rotator/cloud-run/rotate-service-account/README.md
> +RotateServiceAccount is deployed to Cloud Run applying Terraform config stored in [./terraform directory](../../../../configs/terraform). `terraform apply` is executed automatically on every PR chang
```suggestion
RotateServiceAccount is deployed to Cloud Run applying Terraform config stored in [`./terraform` directory](../../../../configs/terraform). `terraform apply` is executed automatically on every PR changing Terraform `.tf` files belonging to the application. 
```

2023-08-29 14:41 UTC, dekiel requested changes
I don't think names are more generic now.

2023-08-30 14:55 UTC, dekiel approved these changes

2023-08-31 08:05 UTC, IwonaLanger approved these changes

2023-08-31 08:08 UTC, merged