cleanup: remove more deadcode
kyma-project/test-infra pull request #9179
Opened 2023-10-24 12:04 UTC by Ressetkk

/kind cleanup
/area ci

/this-is-fine

**Description**

#7386

2023-10-24 14:45 UTC, dekiel requested changes

2023-10-24 14:45 UTC, dekiel commented on prow/plugins.yaml
Automated approver plugin is used.

2023-10-24 14:48 UTC, Ressetkk commented on prow/plugins.yaml
But that doesn't mean we should keep duplicated fields in the YAML. Check again.

2023-10-25 08:54 UTC, dekiel submitted a review, later dismissed

2023-10-25 11:42 UTC, IwonaLanger approved these changes

2023-10-25 14:25 UTC, dekiel submitted a review, later dismissed

2023-10-26 09:35 UTC, halamix2 approved these changes

2023-10-26 09:38 UTC, IwonaLanger approved these changes

2023-10-26 09:45 UTC, barchw approved these changes

2023-10-26 10:11 UTC, lindnerby approved these changes

2023-10-26 10:44 UTC, marcobebway approved these changes

2023-10-26 10:45 UTC, merged