cleanup: moving jobs to repository-based structure p2
kyma-project/test-infra pull request #9212
Opened 2023-10-27 14:33 UTC by Ressetkk

/kind cleanup
/area ci

To further increase the maintainability and distribute ownerships in more sane way I'm moving ProwJobs into specific directories, which follow the organisation/repository pattern under `prow/jobs` directory for now. Work is split into multiple PRs to reduce the number of teams to ping.

No changes in the definitions, only moving files between directories.

#7386

2023-10-27 14:39 UTC, VOID404 approved these changes

2023-10-27 14:42 UTC, barchw approved these changes

2023-10-27 14:43 UTC, k15r submitted a review, later dismissed

2023-10-27 14:43 UTC, Cortey approved these changes

2023-10-28 16:03 UTC, lindnerby submitted a review, later dismissed

2023-10-30 06:16 UTC, Sawthis approved these changes

2023-10-30 09:41 UTC, ognyvrac requested changes
CODEOWNERS still mentions /prow/jobs/incubator/

2023-10-30 09:50 UTC, Ressetkk commented
> CODEOWNERS still mentions /prow/jobs/incubator/

It will be adjusted after all directories are organized in next batch

2023-10-30 14:02 UTC, ognyvrac approved these changes

2023-10-30 14:04 UTC, ivantenevvasilev approved these changes

2023-10-30 14:12 UTC, PetarTodorovv submitted a review, later dismissed

2023-10-30 15:35 UTC, janmedrek submitted a review, later dismissed

2023-10-31 08:38 UTC, dzahariev approved these changes

2023-10-31 08:39 UTC, Sawthis approved these changes

2023-10-31 08:39 UTC, Cortey approved these changes

2023-10-31 08:43 UTC, barchw approved these changes

2023-10-31 08:55 UTC, janmedrek approved these changes

2023-10-31 08:59 UTC, lindnerby approved these changes

2023-10-31 09:01 UTC, k15r approved these changes

2023-10-31 10:48 UTC, VOID404 approved these changes

2023-10-31 10:56 UTC, merged