remove Grafana
kyma-project/test-infra pull request #9398
Opened 2023-11-27 13:59 UTC by halamix2

**Description**

Changes proposed in this pull request:

- remove Grafana

**Related issue(s)**

/kind chore
/area telemetry

2023-11-27 15:05 UTC, halamix2 commented
/test sll

2023-11-27 15:05 UTC, halamix2 commented
/test all

2023-11-27 15:12 UTC, halamix2 commented
/test all

2023-11-27 15:16 UTC, halamix2 commented
/test all

2023-11-28 07:10 UTC, Sawthis requested changes
Please remove githubissues from .koapps.yaml and resolve conflicts.

2023-11-28 08:40 UTC, Sawthis approved these changes

2023-11-28 08:47 UTC, Disper submitted a review, later dismissed

2023-11-28 08:48 UTC, grego952 submitted a review, later dismissed

2023-11-28 08:49 UTC, mmitoraj commented on docs/prow/prow-monitoring.md
> +Stackdriver Monitoring provides information about overall [status](https://app.google.stackdriver.com/uptime?project=sap-kyma-prow-workloads)
```suggestion
Stackdriver Monitoring provides information about the overall [status](https://app.google.stackdriver.com/uptime?project=sap-kyma-prow-workloads).
```

2023-11-28 08:56 UTC, Sawthis approved these changes

2023-11-28 09:28 UTC, Disper approved these changes

2023-11-28 11:11 UTC, Sawthis approved these changes

2023-11-28 11:23 UTC, grego952 approved these changes

2023-11-28 11:24 UTC, merged