Add workload identity federation to terraform config
kyma-project/test-infra pull request #9942
Opened 2024-02-22 18:00 UTC by KacperMalachowski

**Description**

Changes proposed in this pull request:

- Create workload identity federation with actual names
- Use custom module to create it, as gh-oidc from google is creating principalSet and there is no other maintained module
- Do not cover github variables as it require custom personal access token with `administration: write` permisison is need

**Related issue(s)**

/kind bug
/area automation
/test all

2024-02-23 06:44 UTC, Sawthis requested changes

2024-02-23 06:44 UTC, Sawthis commented on configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
> +# }
Do you need to keep this commented code? It can be takes from git history if it will be needed.

2024-02-23 06:44 UTC, Sawthis commented on configs/terraform/environments/prod/gcp-workfload-identity-federation.tf
> +# }
Do you need to keep this commented code? It can be takes from git history if it will be needed.

2024-02-23 07:00 UTC, KacperMalachowski commented
Removed commented code, but we need to keep in mind: https://stackoverflow.com/questions/77214899/permission-needed-to-create-an-environment-from-a-github-actions-workflow

2024-02-23 08:37 UTC, dekiel commented on configs/terraform/modules/gcp-workload-identity-federation/main.tf
> +  member             = "principalSet://iam.googleapis.com/${google_iam_workload_identity_pool.main.name}/${each.value.attribute}"
I think using `principalSet` instead `principal` was the cause of the issues when we try to use a google provided module.

2024-02-26 10:36 UTC, dekiel approved these changes

2024-02-26 12:53 UTC, merged